num1 = int(input("เลขตัวที่ 1 : "))
num2 = int(input("เลขตัวที่ 2 : "))
print(num1, "+", num2, "=", num1+num2)
print(num1, "-", num2, "=", num1-num2)
print(num1, "*", num2, "=", num1*num2)
print(num1, "/", num2, "=", num1/num2)